export const columns = [
  { field: "id", headerName: "ID", width: 70 },
  { field: "name", headerName: "Name", width: 130 },
  { field: "cashbackEnabled", headerName: "Cashback Enabled", width: 150 },
  { field: "cashbackType", headerName: "cashback Type", width: 130 },
  { field: "cashbackPercent", headerName: "Cashback ", width: 100 },
  { field: "isFeatured", headerName: "Is Featured", width: 100 },
  { field: "visits", headerName: "visit", width: 70 },
  { field: "rating", headerName: "Rating", width: 80 },
  { field: "clicks", headerName: "Clicks", width: 80 },
  { field: "status", headerName: "status", width: 100 },
];

export const rows = [
  {
    id: 1,
    name: "Ashsis",
    cashbackEnabled: "no",
    cashbackType: "cashback",
    cashbackPercent: "50.00",
    isFeatured: "no",
    visits: 500,
    clicks: 500,
    rating: 5,
    status: "draft",
  },
  {
    id: 1,
    name: "Ashsis",
    cashbackEnabled: "no",
    cashbackType: "cashback",
    cashbackPercent: "50.00",
    isFeatured: "no",
    visits: 500,
    clicks: 500,
    rating: 5,
    status: "draft",
  },
  {
    id: 1,
    name: "Ashsis",
    cashbackEnabled: "no",
    cashbackType: "cashback",
    cashbackPercent: "50.00",
    isFeatured: "no",
    visits: 500,
    clicks: 500,
    rating: 5,
    status: "draft",
  },
  {
    id: 1,
    name: "Ashsis",
    cashbackEnabled: "no",
    cashbackType: "cashback",
    cashbackPercent: "50.00",
    isFeatured: "no",
    visits: 500,
    clicks: 500,
    rating: 5,
    status: "draft",
  },
  {
    id: 1,
    name: "Ashsis",
    cashbackEnabled: "no",
    cashbackType: "cashback",
    cashbackPercent: "50.00",
    isFeatured: "no",
    visits: 500,
    clicks: 500,
    rating: 5,
    status: "draft",
  },
  {
    id: 1,
    name: "Ashsis",
    cashbackEnabled: "no",
    cashbackType: "cashback",
    cashbackPercent: "50.00",
    isFeatured: "no",
    visits: 500,
    clicks: 500,
    rating: 5,
    status: "draft",
  },
  {
    id: 1,
    name: "Ashsis",
    cashbackEnabled: "no",
    cashbackType: "cashback",
    cashbackPercent: "50.00",
    isFeatured: "no",
    visits: 500,
    clicks: 500,
    rating: 5,
    status: "draft",
  },
  {
    id: 1,
    name: "Ashsis",
    cashbackEnabled: "no",
    cashbackType: "cashback",
    cashbackPercent: "50.00",
    isFeatured: "no",
    visits: 500,
    clicks: 500,
    rating: 5,
    status: "draft",
  },
  {
    id: 1,
    name: "Ashsis",
    cashbackEnabled: "no",
    cashbackType: "cashback",
    cashbackPercent: "50.00",
    isFeatured: "no",
    visits: 500,
    clicks: 500,
    rating: 5,
    status: "draft",
  },
  {
    id: 1,
    name: "Ashsis",
    cashbackEnabled: "no",
    cashbackType: "cashback",
    cashbackPercent: "50.00",
    isFeatured: "no",
    visits: 500,
    clicks: 500,
    rating: 5,
    status: "draft",
  },
  {
    id: 1,
    name: "Ashsis",
    cashbackEnabled: "no",
    cashbackType: "cashback",
    cashbackPercent: "50.00",
    isFeatured: "no",
    visits: 500,
    clicks: 500,
    rating: 5,
    status: "draft",
  },
];
